apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  title: ${{values.component_id | dump}}
  description: ${{values.description | dump}}
spec:
  type: documentation
  lifecycle: experimental
  owner: ${{values.owner | dump}}