apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python_copier_template_ui
  title: Python Copier Template UI
  description: Create a project based on this template using Copier
  tags:
    - recommended
    - techdocs
    - mkdocs
spec:
  owner: kqd14687
  type: documentation

  parameters:
    - title: Project Details
      required:
        - repoUrl
        - description
        - owner
      properties:
        repoUrl:
          title: Repository Name and Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        description:
          title: Description
          type: string
          description: A short description of your project
        owner:
          title: Owner
          type: string
          description: Owner of the component in the Developer Portal Software Catalogue.
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              - User
    - title: Template Options
      properties:
        docker:
          title: Publish Docker container?
          description: |
            Would you like to publish your project in a Docker container?
            You should select this if you are making a service.
          type: boolean
          default: false
        docs:
          title: Documentation
          description: |
            How would you like to document your project?
            You can start with just a README and change your answer to add a sphinx project later.
          type: string
          default: README
          enum:
            - README
            - sphinx


  # This template is meant to be used on top of an existing template.
  # By adding the following and fetching from an absolute URL you can
  # add in the docs template
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:copier
      input:
        url: .
        values:        
          destination: ${{ parameters.repoUrl | parseRepoUrl }}

          package_name: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') | replace('-', '_') }}
          description: ${{ parameters.description }}
          git_platform: ${{ parameters.repoUrl | parseRepoUrl | pick('host') }}
          github_org: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo_name: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
          distribution_name: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') | replace('-', '_') }}
          author_name: ${{ user.entity.metadata.name }}
          author_email: ${{ user.entity.spec.profile.email }}
          component_owner: ${{ parameters.owner }}
          docker: ${{ parameters.docker }}
          docs_type: ${{ parameters.docs_type }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
