name: Install requirements
description: Install uv, use it to install dependencies and report what was installed
inputs:
  python-version:
    description: Python version to install, default is from Dockerfile
    default: "dev"
  uv-sync:
    description: Parameters to pass to uv sync
    default: "--locked"

runs:
  using: composite
  steps:
    - name: Get version of python
      run: |
        PYTHON_VERSION="${{ inputs.python-version }}"
        if [ $PYTHON_VERSION == "dev" ]; then
          # python version from Dockerfile, removing potential pinned sha
          PYTHON_VERSION=$(sed -Ene "s/ARG PYTHON_VERSION=([0-9\.]+).*/\1/p" Dockerfile)
        fi
        echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"
      shell: bash

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        activate-environment: true

    - name: Install packages
      run: uv sync ${{ inputs.uv-sync }}
      shell: bash

    - name: Report what was installed
      run: uv pip freeze
      shell: bash
