name: Install requirements
description: Install a version of python then call pip install and report what was installed
inputs:
  python-version:
    description: Python version to install, default is from Dockerfile
    default: "dev"
  pip-install:
    description: Parameters to pass to uv pip install
    default: "$([ -f dev-requirements.txt ] && echo '-c dev-requirements.txt') -e .[dev]"

runs:
  using: composite
  steps:
    - name: Get version of python
      run: |
        PYTHON_VERSION="${{ inputs.python-version }}"
        if [ $PYTHON_VERSION == "dev" ]; then
          # python version from Dockerfile, removing potential pinned sha
          PYTHON_VERSION=$(sed -Ene "s/ARG PYTHON_VERSION=([0-9\.]+).*/\1/p" Dockerfile)
        fi
        echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"
      shell: bash

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install packages
      run: uv pip install ${{ inputs.pip-install }}
      shell: bash

    - name: Report what was installed
      run: uv pip list
      shell: bash

    - name: Add venv path to Github environment
      run: echo "VENV_PATH=.venv" >> $GITHUB_ENV
      shell: bash

    - name: Add venv path to Github Path
      run: echo "${{ env.VENV_PATH }}/bin:$PATH" >> $GITHUB_PATH
      shell: bash
