on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Avoid git conflicts when tag and branch pushed at same time
        if: github.ref_type == 'tag'
        run: sleep 60

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - name: Install system packages
        run: sudo apt-get install graphviz

      - name: Install python packages
        uses: ./.github/actions/install_requirements

      - name: Build docs
        run: tox -e docs

      - name: Remove environment.pickle
        run: rm build/html/.doctrees/environment.pickle

      - name: Upload built docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: build
