on:
  workflow_call:
    inputs:
      hatch:
        type: string
        description: What to run under hatch
        required: true


jobs:
  run:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python packages
        uses: ./.github/actions/install_requirements

      - name: Run hatch
        run: |
          IFS=',' read -ra SCRIPTS <<< "${{ inputs.hatch }}"
          for script in "${SCRIPTS[@]}"; do
            echo "Running $script"
            hatch run $script
          done
