on:
  workflow_call:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Download container artifact
        uses: actions/download-artifact@v4
        with:
          name: container
          path: container
          
      - name: Create tags for publishing image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Push cached image to container registry
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        # This does not build the image again, it will find the image in the
        # Docker cache and publish it
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
