name: CI

on:
  push:
    tags:
      - '*'

jobs:
  lint:
    uses: ./.github/workflows/_tox.yml
    with:
      tox: pre-commit

  test:
    uses: ./.github/workflows/_test.yml
    with:
      python-version: dev
      runs-on: ubuntu-latest
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  docs:
    uses: ./.github/workflows/_docs.yml
    permissions:
      contents: write

  release:
    needs: docs
    uses: ./.github/workflows/_release.yml
    permissions:
      contents: write
